package com.sentinel.common.domain.enums;

/**
 * Types of security alerts generated by the analytics engine.
 * Replaces magic strings for type-safety and consistency.
 */
public enum AlertType {
    DOS,
    BRUTE_FORCE,
    PATTERN_MATCH
}
