# --- SERVER ---
server.port=8083

# --- DATASOURCE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel_db
spring.datasource.username=sentinel
spring.datasource.password=sentinel_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- RESILIENCE4J CIRCUIT BREAKER ---
resilience4j.circuitbreaker.instances.reportService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.reportService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.reportService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.reportService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.reportService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.reportService.failureRateThreshold=50

# --- JWT SECURITY ---
jwt.secret=${JWT_SECRET:SuperSecretDefaultKeyForLocalDevelopmentMakeSureItIs256BitsAtLeast000000000000000000}

# --- RABBITMQ (needed for sentinel-core consumer) ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

# --- SENTINEL CUSTOM ---
sentinel.queue.ingress=logs.ingress.key
sentinel.analysis.dos-threshold=100
sentinel.analysis.bf-threshold=10
