# --- SERVER ---
server.port=8083
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# --- DATASOURCE ---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sentinel_db}
spring.datasource.username=${DB_USERNAME:sentinel}
spring.datasource.password=${DB_PASSWORD:sentinel_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- RESILIENCE4J CIRCUIT BREAKER ---
resilience4j.circuitbreaker.instances.reportService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.reportService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.reportService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.reportService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.reportService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.reportService.failureRateThreshold=50

# --- JWT SECURITY ---
jwt.secret=${JWT_SECRET:SuperSecretDefaultKeyForLocalDevelopmentMakeSureItIs256BitsAtLeast000000000000000000}

# --- RABBITMQ ---
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:user}
spring.rabbitmq.password=${RABBITMQ_PASS:password}

# --- SENTINEL CUSTOM ---
sentinel.queue.ingress=logs.ingress.key
sentinel.analysis.dos-threshold=100
sentinel.analysis.bf-threshold=10

# --- CORS ---
sentinel.cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173}
