# --- SERVER ---
server.port=8080

# --- DATASOURCE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel_db
spring.datasource.username=sentinel
spring.datasource.password=sentinel_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- RABBITMQ ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password
# JSON serialization
spring.rabbitmq.listener.simple.message-converter=jsonMessageConverter

# --- SENTINEL CUSTOM PARAMETERS ---
sentinel.jwt.secret=MySecretKeyForSigningHmacSha256
sentinel.analysis.dos-threshold=100
sentinel.analysis.window-seconds=60
sentinel.queue.ingress=sentinel.queue.ingress
