# --- SERVER ---
server.port=8082

# --- DATASOURCE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel_db
spring.datasource.username=sentinel
spring.datasource.password=sentinel_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- RABBITMQ ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password
# Automated JSON deserialization
spring.rabbitmq.listener.simple.message-converter=jsonMessageConverter

# --- SENTINEL CUSTOM ---
sentinel.queue.ingress=logs.ingress.key
