spring.application.name=sentinel-agent

# RabbitMQ Connection Details
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:user}
spring.rabbitmq.password=${RABBITMQ_PASS:password}

# Sentinel SIEM Custom Routing Keys
sentinel.queue.ingress=logs.ingress.key

# Time-Shift replay speedup factor (e.g., 100 means 100x faster than real-time)
sentinel.agent.speedup=100

# Server configuration
server.port=8081
