spring.application.name=sentinel-agent

# RabbitMQ Connection Details (Matches docker-compose.yml)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

# Sentinel SIEM Custom Routing Keys
sentinel.queue.ingress=logs.ingress.key

# Time-Shift replay speedup factor (e.g., 100 means 100x faster than real-time)
sentinel.agent.speedup=100

# Server configuration
server.port=8081
